### ISSUE TITLE
Does not work for metro Phone

### ISSUE THREAD

**Issue by Jasoniceboy** [LITdevs/salad-mobile#1]
Do you want proof:
![AD7B4759-B14B-4E9D-B456-E5BFF9F3ACEB](https://user-images.githubusercontent.com/99864373/154423577-af41cc97-a2dd-4a7b-9642-e0364101805e.jpeg)
![E13D1E8A-1902-4BEC-B875-2B60436496A2](https://user-images.githubusercontent.com/99864373/154423587-cc60b02c-8e4a-46e1-82c2-801a1dd65853.jpeg) there is proof.

**Comment by Vukkyy** [comment]
Press the hamburger menu in the top right.
